# Generated by Django 5.0.7 on 2024-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_remove_car_photo_remove_tour_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
